---
- name: Configure IP addresses on routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set IP address for Router 1
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - ip address 192.168.1.1 255.255.255.0
        parents: interface GigabitEthernet0/0
      register: result_router1

    - name: Set IP address for Router 2
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - ip address 192.168.1.2 255.255.255.0
        parents: interface GigabitEthernet0/0
      register: result_router2

    - name: Check if configuration was applied successfully for Router 1
      debug:
        msg: "Configuration for Router 1 applied successfully"
      when: result_router1.changed

    - name: Check if configuration was applied successfully for Router 2
      debug:
        msg: "Configuration for Router 2 applied successfully"
      when: result_router2.changed

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios

# syntax ansible-playbook hosts.yml
# ansible-playbook -i inventory_file playbook.yml